# Generated by Django 5.2.15 on 2026-06-23 10:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('locations', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('months', models.PositiveIntegerField()),
                ('depreciation_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('depreciation_type', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('amount', 'Amount')], default='amount', max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_active_depreciation_profile_name')],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('eol_months', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'asset', 'deleted_at__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='asset_models', to='catalogue.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_models', to='catalogue.manufacturer')),
                ('depreciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_models', to='assets.depreciationprofile')),
            ],
            options={
                'ordering': ['name', 'model_number'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_tag', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('serial', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('requestable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assets', to='assets.asset')),
                ('assigned_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_assets', to='locations.location')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assets', to='locations.location')),
                ('status_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalogue.statuslabel')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='suppliers.supplier')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetmodel')),
            ],
            options={
                'ordering': ['asset_tag'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_tag',), name='uniq_active_asset_tag')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'model_number'), name='uniq_active_asset_model_name_number'),
        ),
    ]
