# Generated by Django 5.2.15 on 2026-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_checked_out_at_asset_expected_checkin_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organisations.company'),
        ),
    ]
