# Generated by Django 5.2.15 on 2026-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(choices=[('asset', 'Asset'), ('accessory', 'Accessory'), ('consumable', 'Consumable'), ('component', 'Component'), ('license', 'License')], max_length=32)),
                ('require_acceptance', models.BooleanField(default=False)),
                ('use_default_eula', models.BooleanField(default=False)),
                ('checkin_email', models.BooleanField(default=False)),
                ('alert_on_response', models.BooleanField(default=False)),
                ('tag_color', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'category_type'), name='uniq_active_category_name_type')],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('support_url', models.URLField(blank=True)),
                ('warranty_lookup_url', models.URLField(blank=True)),
                ('tag_color', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_active_manufacturer_name')],
            },
        ),
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('deployable', models.BooleanField(default=True)),
                ('pending', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('default_label', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_active_status_label_name')],
            },
        ),
    ]
