# Generated by Django 5.2.15 on 2026-06-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('organisations', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('assigned_quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'component', 'deleted_at__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='catalogue.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='organisations.company')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'company'), name='uniq_active_component_name_company')],
            },
        ),
    ]
