# Generated by Django 5.2.15 on 2026-06-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intake', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntakeInvoiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('partially_reviewed', 'Partially Reviewed'), ('partially_approved', 'Partially Approved'), ('approved_complete', 'Approved Complete'), ('rejected', 'Rejected'), ('unsupported_items_pending', 'Unsupported Items Pending')], default='extracted', max_length=32)),
                ('extracted_invoice_data', models.JSONField(blank=True, default=dict)),
                ('invoice_metadata', models.JSONField(blank=True, default=dict)),
                ('review_summary', models.JSONField(blank=True, default=dict)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_review', to='ai_intake.aiintakejob')),
                ('legacy_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_reviews', to='ai_intake.aiintakedraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIIntakeLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('raw_description', models.TextField(blank=True)),
                ('normalized_description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manufacturer_hint', models.CharField(blank=True, max_length=255)),
                ('model_hint', models.CharField(blank=True, max_length=255)),
                ('serial_hint', models.CharField(blank=True, max_length=255)),
                ('part_number_hint', models.CharField(blank=True, max_length=255)),
                ('reference_hint', models.CharField(blank=True, max_length=255)),
                ('predicted_inventory_type', models.CharField(blank=True, max_length=32)),
                ('predicted_category_name', models.CharField(blank=True, max_length=255)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('classification_rationale', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('extracted', 'Extracted'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], default='extracted', max_length=24)),
                ('final_inventory_type', models.CharField(blank=True, max_length=32)),
                ('final_category_name', models.CharField(blank=True, max_length=255)),
                ('requires_review', models.BooleanField(default=True)),
                ('unsupported_for_approval', models.BooleanField(default=False)),
                ('created_record_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extraction_payload', models.JSONField(blank=True, default=dict)),
                ('reviewer_feedback', models.JSONField(blank=True, default=dict)),
                ('created_record_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intake_line_items', to='contenttypes.contenttype')),
                ('invoice_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ai_intake.aiintakeinvoicereview')),
            ],
            options={
                'ordering': ['invoice_review_id', 'line_number', 'id'],
            },
        ),
    ]
