# Generated by Django 5.2.15 on 2026-06-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intake', '0002_aiintakeinvoicereview_aiintakelineitem'),
        ('organisations', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintakeinvoicereview',
            name='review_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intake_invoice_reviews', to='organisations.company'),
        ),
        migrations.CreateModel(
            name='AIIntakeClassificationSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_inventory_type', models.CharField(blank=True, max_length=32)),
                ('final_inventory_type', models.CharField(max_length=32)),
                ('predicted_category_name', models.CharField(blank=True, max_length=255)),
                ('final_category_name', models.CharField(blank=True, max_length=255)),
                ('raw_description', models.TextField(blank=True)),
                ('normalized_item_name', models.CharField(max_length=255)),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('order_number_snapshot', models.CharField(blank=True, max_length=255)),
                ('purchase_date_snapshot', models.CharField(blank=True, max_length=50)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('correction_applied', models.BooleanField(default=False)),
                ('unsupported_predicted', models.BooleanField(default=False)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intake_classification_signals', to='organisations.company')),
                ('source_draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_signal', to='ai_intake.aiintakedraft')),
                ('source_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_signal', to='ai_intake.aiintakelineitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intake_classification_signals', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
