# Generated by Django 5.2.15 on 2026-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intake', '0003_aiintakeinvoicereview_review_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintakelineitem',
            name='review_status',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('unsupported', 'Unsupported')], default='extracted', max_length=24),
        ),
    ]
