# Generated by Django 5.2.15 on 2026-06-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='$', max_length=8)),
                ('address', models.CharField(blank=True, max_length=191)),
                ('address2', models.CharField(blank=True, max_length=191)),
                ('city', models.CharField(blank=True, max_length=191)),
                ('state', models.CharField(blank=True, max_length=191)),
                ('country', models.CharField(blank=True, max_length=191)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=35)),
                ('fax', models.CharField(blank=True, max_length=35)),
                ('ldap_ou', models.CharField(blank=True, max_length=191)),
                ('tag_color', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uniq_active_location_name')],
            },
        ),
    ]
